name: K6 Load Test Pipeline

on:
  push:
    branches:
      - master

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Levantar servidor
        run: |
          npm start &
          sleep 10

      - name: Instalar K6
        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install k6

      - name: Ejecutar K6
        run: k6 run load-test.js