name: K6 Load Test Pipeline

on:
  push:
    branches:
      - master

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      # Clonar repositorio
      - name: Clonar repositorio
        uses: actions/checkout@v3

      # Instalar Node
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalar dependencias (FIX ERROR ERESOLVE)
      - name: Instalar dependencias
        run: npm install --legacy-peer-deps

      # Levantar servidor
      - name: Levantar servidor
        run: |
          npm start &
          sleep 15

      # Instalar K6
      - name: Instalar K6
        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install k6

      # Ejecutar pruebas de carga
      - name: Ejecutar pruebas K6
        run: k6 run load-test.js