name: K6 Load Test Pipeline

on:
  push:
    branches:
      - master

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      # Clonar repositorio
      - name: Clonar repositorio
        uses: actions/checkout@v4

      # Instalar Node
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Instalar dependencias (FIX ERROR ERESOLVE)
      - name: Instalar dependencias
        run: npm install --legacy-peer-deps

      # Levantar servidor
      - name: Levantar servidor
        run: |
          npm start &
          sleep 15

      # Instalar K6
      - name: Instalar K6
        run: |
          sudo apt update
          sudo apt install -y k6

      # 🚀 Ejecutar pruebas y enviar a Grafana
      - name: Ejecutar pruebas K6 con Grafana
        run: |
          K6_PROMETHEUS_RW_SERVER_URL=${{ secrets.GRAFANA_URL }} \
          K6_PROMETHEUS_RW_USERNAME=${{ secrets.GRAFANA_USER }} \
          K6_PROMETHEUS_RW_PASSWORD=${{ secrets.GRAFANA_API_KEY }} \
          k6 run --out experimental-prometheus-rw load-test.js